
// PWA Service Worker Registration
// This script registers the service worker generated by vite-plugin-pwa.

if ('serviceWorker' in navigator) {
    window.addEventListener('load', () => {
        // Registers /sw.js (default output of vite-plugin-pwa)
        navigator.serviceWorker.register('/sw.js', { scope: '/' })
            .then(registration => {
                console.log('SW registered: ', registration);
            })
            .catch(registrationError => {
                console.log('SW registration failed: ', registrationError);
            });
    });
}
