
// PWA Service Worker Registration
// This script registers the service worker generated by vite-plugin-pwa.

if ('serviceWorker' in navigator) {
    if (import.meta.env.DEV) {
        // Unregister service worker in development to prevent caching issues
        navigator.serviceWorker.getRegistrations().then(registrations => {
            for (let registration of registrations) {
                registration.unregister();
                console.log('SW unregistered in Dev mode');
            }
        });
    } else {
        window.addEventListener('load', () => {
            navigator.serviceWorker.register('/sw.js', { scope: '/' })
                .then(registration => {
                    console.log('SW registered: ', registration);
                })
                .catch(registrationError => {
                    console.log('SW registration failed: ', registrationError);
                });
        });
    }
}
